#!/bin/bash

if [ -z ${TRANSMISSION_SEED_QUEUE} ]; then
  TRANSMISSION_ENABLE_SEED_QUEUE=false
else
  TRANSMISSION_ENABLE_SEED_QUEUE=true
fi

if [ -z ${TRANSMISSION_QUEUE_STALLED_MINUTES} ]; then
  TRANSMISSION_ENABLE_STALLED=false
else
  TRANSMISSION_ENABLE_STALLED=true
fi

if [ -z ${TRANSMISSION_DOWNLOAD_QUEUE_SIZE} ]; then
  TRANSMISSION_ENABLE_DOWNLOAD_QUEUE=false
else
  TRANSMISSION_ENABLE_DOWNLOAD_QUEUE=true
fi

cat <<EOF>>$TRANSMISSION_CONFIG
    ,"download-queue-enabled": ${TRANSMISSION_ENABLE_DOWNLOAD_QUEUE}
    ,"download-queue-size": ${TRANSMISSION_DOWNLOAD_QUEUE_SIZE:=5}
    ,"queue-stalled-enabled": ${TRANSMISSION_ENABLE_STALLED}
    ,"queue-stalled-minutes": ${TRANSMISSION_QUEUE_STALLED_MINUTES:=30}
    ,"seed-queue-enabled": ${TRANSMISSION_ENABLE_SEED_QUEUE}
    ,"seed-queue-size": ${TRANSMISSION_SEED_QUEUE:=10}
EOF
